using Godot;
using System;
using System.Collections.Generic;

public static class BeepParticleGenerator
{
    private const string CatalogPath = "res://addons/beep_game_builder_cs/catalogs/particle_presets.json";

    public static string CreateParticleById(string pid, bool overwrite = false)
    {
        var data = BeepFileUtils.LoadJson(CatalogPath);
        Godot.Collections.Dictionary preset = null;
        if (data.TryGetValue("presets", out var pv) && pv.VariantType == Variant.Type.Array)
            foreach (var p in pv.AsGodotArray())
                if ((string)p.AsGodotDictionary()["id"] == pid) { preset = p.AsGodotDictionary(); break; }
        if (preset == null) return CreateParticleSceneTemplate(pid, overwrite);

        var sceneName = (string)preset.GetValueOrDefault("scene_name", pid);
        var path = $"res://scenes/effects/particles/{sceneName}.tscn";
        if (!overwrite && BeepFileUtils.FileExists(path)) { BeepFileUtils.Log($"Skipped particle: {path}"); return path; }

        var p2d = new GpuParticles2D { Name = (string)preset.GetValueOrDefault("display_name", pid) };
        p2d.Amount = preset["amount"].AsInt32();
        p2d.Lifetime = preset["lifetime"].AsSingle();
        p2d.OneShot = (bool)preset["one_shot"];
        p2d.Explosiveness = (float)preset["explosiveness"].AsSingle();

        var mat = new ParticleProcessMaterial();
        mat.Spread = (float)preset["spread"].AsSingle();
        var grav = preset["gravity"].AsGodotDictionary();
        mat.Gravity = new Vector3((float)grav["x"].AsSingle(), (float)grav["y"].AsSingle(), (float)grav["z"].AsSingle());
        mat.ScaleMin = preset["scale_min"].AsSingle();
        mat.ScaleMax = preset["scale_max"].AsSingle();
        mat.Color = new Color((string)preset["color"]);
        p2d.ProcessMaterial = mat;

        var packed = new PackedScene(); packed.Pack(p2d);
        ResourceSaver.Save(packed, path);
        BeepFileUtils.Log($"Created particle: {path}"); return path;
    }

    private static string CreateDefaultParticle(string pid, bool overwrite)
    {
        var path = $"res://scenes/effects/particles/{pid}.tscn";
        if (!overwrite && BeepFileUtils.FileExists(path)) { BeepFileUtils.Log($"Skipped: {path}"); return path; }
        var p = new GpuParticles2D { Name = char.ToUpper(pid[0]) + pid[1..], Amount = 48, OneShot = true, Explosiveness = 0.85f, Lifetime = 0.7f };
        var mat = new ParticleProcessMaterial { Spread = 180f, Gravity = new Vector3(0, 120, 0), InitialVelocityMin = 70, InitialVelocityMax = 140 };
        p.ProcessMaterial = mat;
        var packed = new PackedScene(); packed.Pack(p); ResourceSaver.Save(packed, path);
        BeepFileUtils.Log($"Created default particle: {path}"); return path;
    }

    public static void CreateAllParticles(bool overwrite = false)
    {
        var data = BeepFileUtils.LoadJson(CatalogPath);
        if (!data.TryGetValue("presets", out var pv) || pv.VariantType != Variant.Type.Array) return;
        foreach (var p in pv.AsGodotArray()) CreateParticleById((string)p.AsGodotDictionary()["id"], overwrite);
        BeepFileUtils.RefreshFilesystem();
    }

    public static string CreateParticleHelperScript(bool overwrite = false)
    {
        var path = "res://scripts/effects/particle_effects.gd";
        var code = @"## ParticleEffects - generated by Beep Game Builder (C#)
class_name ParticleEffects
extends Node

static func spawn(scene_path: String, parent: Node, position: Vector2 = Vector2.ZERO, one_shot: bool = true) -> GpuParticles2D:
	var packed := load(scene_path) as PackedScene
	if not packed: push_error(""ParticleEffects: could not load "" + scene_path); return null
	var instance := packed.instantiate() as GpuParticles2D
	if not instance: return null
	parent.add_child(instance); instance.global_position = position
	if one_shot: instance.one_shot = true; instance.emitting = true
	else: instance.emitting = true
	return instance

static func spawn_burst(scene_path: String, parent: Node, position: Vector2 = Vector2.ZERO) -> GpuParticles2D:
	return spawn(scene_path, parent, position, true)

static func cleanup_after(node: Node, seconds: float) -> void:
	if not node: return
	node.get_tree().create_timer(seconds).timeout.connect(node.queue_free)
";
        BeepFileUtils.SafeWriteText(path, code, overwrite); return path;
    }

    /// <summary>Copy a particle scene template (.tscn) to the project.</summary>
    public static string CreateParticleSceneTemplate(string templateId, bool overwrite = false)
    {
        var srcPath = $"res://addons/beep_game_builder_cs/templates/particles/{templateId}.tscn";
        var targetPath = $"res://scenes/effects/particles/{templateId}.tscn";

        if (!overwrite && Godot.FileAccess.FileExists(targetPath))
            return targetPath + " (exists)";

        var dir = targetPath.GetBaseDir();
        if (!DirAccess.DirExistsAbsolute(dir)) DirAccess.MakeDirRecursiveAbsolute(dir);

        var packed = ResourceLoader.Load<PackedScene>(srcPath);
        if (packed == null) return $"Failed to load: {srcPath}";

        ResourceSaver.Save(packed, targetPath);
        BeepFileUtils.Log($"Created particle: {targetPath}");
        BeepFileUtils.RefreshFilesystem();
        return targetPath;
    }
}
