using Godot;

public static class BeepExportChecklist
{
    public static string CreateExportChecklist(string path = "res://EXPORT_CHECKLIST.md")
    {
        var md = @"# Export Checklist

Generated by Beep Game Builder (C#).

## Project Settings
- [ ] Project name set
- [ ] Main scene set
- [ ] Icons set
- [ ] Input map complete
- [ ] Window/stretch settings reviewed

## Export Presets
- [ ] Export presets configured
- [ ] Debug disabled for release

## Audio
- [ ] Audio buses checked

## Save System
- [ ] Save path tested

## Assets & Licensing
- [ ] License/assets checked

## Testing
- [ ] Controls tested
- [ ] Main menu tested
- [ ] Pause menu tested
- [ ] Scene transitions tested

## Final
- [ ] Version updated
- [ ] Release build exported
";
        BeepFileUtils.SafeWriteText(path, md, true); return path;
    }

    public static bool HasExportPresets() => Godot.FileAccess.FileExists("res://export_presets.cfg");
}
