using Godot;
using System.Collections.Generic;

public static class BeepTweenGenerator
{
    private const string CatalogPath = "res://addons/beep_game_builder_cs/catalogs/tween_presets.json";

    public static string CreateTweenHelper(bool overwrite = false) => CreateTweenHelperSelected(new List<string>(), overwrite);

    public static string CreateTweenHelperSelected(List<string> ids, bool overwrite = false)
    {
        var path = "res://scripts/effects/tween_effects.gd";
        var data = BeepFileUtils.LoadJson(CatalogPath);
        var presets = new Godot.Collections.Array();
        if (data.TryGetValue("presets", out var pv) && pv.VariantType == Variant.Type.Array) presets = pv.AsGodotArray();
        var selected = ids.Count == 0 ? presets : FilterPresets(presets, ids);

        var code = "## TweenEffects - generated by Beep Game Builder (C#)\nclass_name TweenEffects\nextends Node\n\n";
        foreach (var p in selected) code += ((string)p.AsGodotDictionary()["code"]) + "\n\n";

        BeepFileUtils.SafeWriteText(path, code, overwrite); return path;
    }

    private static Godot.Collections.Array FilterPresets(Godot.Collections.Array all, List<string> ids)
    {
        var result = new Godot.Collections.Array();
        foreach (var p in all)
            if (ids.Contains((string)p.AsGodotDictionary()["id"])) result.Add(p);
        return result;
    }
}
