extends SceneTree

const APP = preload("res://addons/beep_game_builder_cs/ecs/GameApp.cs")
const INFO = preload("res://addons/beep_game_builder_cs/core/GameInfo.cs")
const LEVEL_LOADER = preload("res://addons/beep_game_builder_cs/ecs/LevelLoaderComponent.cs")
const TERRAIN = preload("res://tests/fixtures/session_terrain.tscn")
var failures: Array[String] = []
var worlds_built := 0

func _initialize() -> void:
	call_deferred("run")

func check(ok: bool, message: String) -> void:
	if not ok:
		failures.append(message)
		print("[session-lifecycle] FAIL: " + message)

func settle() -> void:
	await process_frame
	await process_frame

func run() -> void:
	var info = INFO.new()
	var directory = "user://session_probe_%s" % Time.get_ticks_usec()
	info.set("SaveDirectory", directory)
	info.set("TimeAxis", 1)
	info.set("BeatsPerDay", 1.0)
	var app = APP.new()
	app.name = "GameApp"
	app.set("Info", info)
	root.add_child(app)
	var saves = app.get("Saves")
	var clock = app.get("Clock")
	check(not clock.call("EndTurn"), "Menu allowed simulation turn")
	saves.call("_Process", 1000.0)
	check(not FileAccess.file_exists(directory + "/autosave.json"), "Menu autosaved an empty session")
	app.call("StartNewSession", "A")
	var loader := Node.new()
	root.add_child(loader)
	saves.call("BeginWorldLoad", loader)
	saves.call("BeginSession", "A")
	await settle()
	check(not saves.get("IsSessionReady") and not saves.call("Save", 0), "Loading session allowed save")
	check(not clock.call("EndTurn"), "Loading session advanced clock")
	saves.call("CompleteWorldLoad", loader, true)
	await settle()
	check(saves.get("IsSessionReady") and app.get("IsGameRunning"), "Successful world did not become ready")
	clock.call("EndTurn")
	app.call("AddSessionScore", 7)
	app.set("LastCheckpointLevel", 5)
	app.set("LastCheckpointPosition", Vector2(12, 25))
	app.call("CompleteLevel", 2)
	saves.call("SetGameData", "run_a", 123)
	check(saves.call("Save", 0), "Ready session could not save")
	check(saves.call("LoadForSceneChange", 0), "Could not queue saved session")
	saves.call("BeginSession", "A")
	app.call("StartNewSession", "B")
	await settle()
	check(int(app.get("SessionScore")) == 0 and int(clock.get("Turn")) == 0, "Stale restore overwrote fresh run")
	check(int(app.get("LastCheckpointLevel")) == -1 and app.get("LastCheckpointPosition") == Vector2.ZERO, "New run kept old checkpoint")
	check(app.call("IsLevelCompleted", 2), "New run cleared lifetime progression")
	check(not saves.get("IsRestorePending") and not saves.get("IsSessionReady"), "Fresh run retained queued restore or premature readiness")
	saves.call("BeginSession", "B")
	await settle()
	check(saves.get("IsSessionReady"), "Fresh B failed to become ready")
	var before = FileAccess.get_file_as_string(directory + "/save_0.json")
	saves.set("IsActive", false)
	check(not saves.call("Save", 0) and not saves.call("SaveAutosave"), "Disabled save manager wrote state")
	check(before == FileAccess.get_file_as_string(directory + "/save_0.json"), "Rejected save altered file")
	saves.set("IsActive", true)
	saves.call("SuspendSession")
	check(not saves.get("CanSave") and not clock.call("EndTurn"), "Suspended scene still runs or saves")
	saves.call("CompleteWorldLoad", loader, false)
	saves.call("BeginSession", "B")
	await settle()
	check(saves.get("IsSessionReady"), "Stale loader completion poisoned the next session")
	saves.call("SuspendSession")
	saves.call("BeginWorldLoad", loader)
	saves.call("BeginSession", "B")
	saves.call("CompleteWorldLoad", loader, false)
	await settle()
	check(not saves.get("IsSessionReady"), "Failed world became ready")
	app.call("StartNewSession", "terrain")
	var host := Node.new()
	root.add_child(host)
	var level_loader = LEVEL_LOADER.new()
	level_loader.set("Levels", [TERRAIN])
	level_loader.connect("LevelLoaded", func(_level):
		host.get_node("SessionTerrain/World").connect("WorldBuilt", func(_size): worlds_built += 1))
	saves.call("BeginSession", "terrain")
	host.add_child(level_loader)
	await settle()
	check(saves.get("IsSessionReady") and worlds_built == 1, "Nested terrain load did not finish exactly once before readiness")
	host.get_node("SessionTerrain/World").set("Seed", 99)
	check(saves.call("Save", 0), "Could not save terrain recipe")
	check(saves.call("LoadForSceneChange", 0), "Could not queue terrain restore")
	host.free()
	host = Node.new()
	root.add_child(host)
	level_loader = LEVEL_LOADER.new()
	level_loader.set("Levels", [TERRAIN])
	level_loader.connect("LevelLoaded", func(_level):
		host.get_node("SessionTerrain/World").connect("WorldBuilt", func(_size): worlds_built += 1))
	saves.call("BeginSession", "terrain")
	host.add_child(level_loader)
	await settle()
	check(saves.get("IsSessionReady") and worlds_built == 2, "Restore also generated a fresh world")
	check(int(host.get_node("SessionTerrain/World").get("Seed")) == 99, "Nested level missed saved recipe")
	host.free()
	saves.call("DeleteSave", 0)
	loader.free()
	app.free()
	print("[session-lifecycle] OK" if failures.is_empty() else "[session-lifecycle] %s failures" % failures.size())
	quit(0 if failures.is_empty() else 1)
