extends SceneTree

const ECS := "res://addons/beep_game_builder_cs/ecs/"
var failures: Array[String] = []

func check(ok: bool, message: String) -> void:
	if not ok:
		failures.append(message)
		push_error(message)

func make(path: String, label: String, parent: Node, properties := {}) -> Node:
	var node: Node = load(ECS + path + ".cs").new()
	node.name = label
	for key in properties: node.set(key, properties[key])
	parent.add_child(node)
	return node

func _initialize() -> void: run.call_deferred()

func run() -> void:
	var host := Node2D.new()
	root.add_child(host)
	var cells := make("grid/GridCellDataComponent", "Cells", host)
	var other := make("grid/GridCellDataComponent", "Other", host)
	var a := Node.new()
	var b := Node.new()
	host.add_child(a)
	host.add_child(b)
	var left := Vector2i(-1, -2)
	var right := Vector2i.ONE
	check(cells.SetChunkPins(a, [left, left]) and cells.GetChunkPinCount(left) == 1, "Duplicate owner demand multiplied pins")
	check(cells.SetChunkPins(b, [left, right]) and cells.GetChunkPinCount(left) == 2, "Overlapping owners lost shared demand")
	var demands: Array = cells.GetPinnedChunks()
	check(demands.size() == 2 and left in demands and right in demands, "Pinned chunk enumeration missed demand")
	demands.clear()
	check(cells.PinnedChunkCount == 2, "Demand enumeration exposed live mutable state")
	var revision: int = cells.GetChunkRevision(left)
	check(not cells.SetChunkAvailable(left, false) and cells.IsChunkAvailable(left), "Pinned chunk was marked unavailable")
	check(cells.GetChunkRevision(left) == revision, "Pinning mutated content revision")
	cells.SetChunkPins(a, [right])
	check(cells.GetChunkPinCount(left) == 1 and cells.GetChunkPinCount(right) == 2, "Replacing an owner's demand changed another owner's pins")
	host.remove_child(b)
	check(not cells.IsChunkPinned(left) and cells.GetChunkPinCount(right) == 1, "Detached owner retained pins")
	b.free()
	cells.ReleaseChunkPins(a)
	check(cells.PinnedChunkCount == 0 and cells.SetChunkAvailable(left, false), "Released chunk stayed pinned")
	cells.SetChunkPins(a, [left])
	check(not cells.IsChunkAvailable(left), "Pin demand silently loaded unavailable data")
	cells.SetChunkAvailable(left, true)
	a.free()
	check(cells.PinnedChunkCount == 0, "Freed owner leaked pins")
	var jobs := make("grid/GridJobQueueComponent", "Jobs", host, {"ChunkCellDataPath": NodePath("../Cells"), "RemoveCompletedJobs": false, "RemoveCancelledJobs": false})
	var observed := [false]
	jobs.JobAdded.connect(func(_id, _kind, _x, _y): observed[0] = cells.IsChunkPinned(left))
	var id: String = jobs.AddJob(Vector2i(-1, -33), "build", 1.0, 0)
	check(observed[0] and cells.IsChunkPinned(left), "JobAdded callback ran before target pinning")
	jobs.SetJobApproachCell(id, Vector2i(32, 32))
	check(cells.IsChunkPinned(right), "Approach chunk was not pinned")
	check(jobs.ClaimJob(id, "worker"), "Could not claim pinned job")
	check(jobs.ReleaseJob(id, "worker") and cells.IsChunkPinned(left), "Requeued job lost its pins")
	jobs.CompleteJob(id, "")
	check(jobs.HasJob(id) and cells.PinnedChunkCount == 0, "Retained completed job pinned terrain")
	id = jobs.AddJob(Vector2i(-1, -33), "clear", 1.0, 0)
	jobs.CancelJob(id, "test")
	check(cells.PinnedChunkCount == 0, "Cancelled job retained pins")
	id = jobs.AddJob(Vector2i(-1, -33), "work", 1.0, 0)
	jobs.SetJobApproachCell(id, Vector2i(32, 32))
	var saved: Array = jobs.GetJobs()
	jobs.ClearJobs()
	check(cells.PinnedChunkCount == 0, "Cleared queue retained pins")
	jobs.LoadJobs(saved, true)
	check(cells.IsChunkPinned(left) and cells.IsChunkPinned(right), "Loaded open job did not restore demand")
	jobs.ChunkCellDataPath = NodePath("../Other")
	check(cells.PinnedChunkCount == 0 and other.IsChunkPinned(left), "Rebinding queue leaked old-world pins")
	host.remove_child(jobs)
	check(other.PinnedChunkCount == 0, "Detached queue retained pins")
	host.add_child(jobs)
	check(other.IsChunkPinned(left), "Reattached queue lost open-job pins")
	jobs.free()
	check(other.PinnedChunkCount == 0, "Freed queue leaked demand")
	var building := Node2D.new()
	host.add_child(building)
	var structure := make("grid/GridObjectComponent", "Structure", building, {
		"ChunkCellDataPath": NodePath("../../Cells"), "Cell": Vector2i(-1, -1),
		"Footprint": Vector2i(34, 34), "BlocksNavigation": false,
		"ReleaseReservedFootprintOnExit": false, "Complete": false})
	check(cells.PinnedChunkCount == 9, "Nonblocking construction footprint did not pin all nine chunks")
	var structure_state: Dictionary = structure.CaptureState()
	structure.SetCell(Vector2i(96, 96))
	check(cells.PinnedChunkCount == 4 and not cells.IsChunkPinned(Vector2i(-1, -1)), "Moving structure retained old footprint pins")
	structure.Footprint = Vector2i.ONE
	check(cells.PinnedChunkCount == 1, "Inspector footprint edit did not refresh demand")
	structure.RestoreState(structure_state)
	check(cells.PinnedChunkCount == 9, "Restored structure lost footprint pins")
	structure.ChunkCellDataPath = NodePath("../../Other")
	check(cells.PinnedChunkCount == 0 and other.PinnedChunkCount == 9, "Structure rebind leaked pins")
	host.remove_child(building)
	check(other.PinnedChunkCount == 0, "Detached structure retained demand when occupancy release was disabled")
	host.add_child(building)
	check(other.PinnedChunkCount == 9, "Reattached structure failed to reacquire pins")
	building.free()
	check(other.PinnedChunkCount == 0, "Demolished structure leaked pins")
	var grid := make("grid/GridProjectionComponent", "Grid", host, {"DrawGrid": false, "TrackMouseCell": false})
	var template := Node2D.new()
	var packed := PackedScene.new()
	check(packed.pack(template) == OK, "Could not pack structure fixture")
	template.free()
	var placement := make("grid/GridPlacementComponent", "Placement", host, {
		"GridPath": NodePath("../Grid"), "CellDataPath": NodePath("../Cells"),
		"PlacementScene": packed, "Footprint": Vector2i(2, 2), "UseMouseInput": false})
	placement.BeginPlacement("structure")
	placement.MovePreviewToCell(Vector2i(31, 31))
	var placed: Node = placement.ConfirmPlacement()
	check(placed != null and cells.PinnedChunkCount == 4, "Placement did not bind the full cross-chunk footprint")
	if placed != null: placed.free()
	placement.free()
	check(cells.PinnedChunkCount == 0, "Placed structure demolition leaked pins")
	var actors := Node2D.new()
	actors.name = "Actors"
	host.add_child(actors)
	make("grid/GridNavigationComponent", "Navigation", host, {"GridPath": NodePath("../Grid")})
	var definition: Resource = load(ECS + "actors/ActorDefinition.cs").new()
	definition.Id = "ambient"
	definition.Scene = load("res://tests/actor_residency_unit.tscn")
	definition.SimulationPolicy = 1
	var registry := make("actors/ActorRegistryComponent", "Registry", host, {"ActorsRootPath": NodePath("../Actors"), "Definitions": [definition], "ChunkCellDataPath": NodePath("../Cells"), "ChunkGridPath": NodePath("../Grid"), "ActorChunkRadius": 0})
	var actor: Node = registry.SpawnActor("ambient", "", grid.CellToWorld(Vector2i(-1, -33)), "npc")
	check(actor != null and cells.GetChunkPinCount(left) == 1, "Actor registration did not pin its negative-coordinate chunk")
	actor.get_parent().global_position = grid.CellToWorld(Vector2i(32, 32))
	actor.SynchronizePosition()
	check(not cells.IsChunkPinned(left) and cells.GetChunkPinCount(right) == 1, "Immediate position synchronization retained old actor chunk")
	registry.ActorChunkRadius = 1
	check(cells.PinnedChunkCount == 9, "Actor padding did not pin its neighboring chunks")
	registry.RefreshChunkPins()
	check(cells.GetChunkPinCount(right) == 1, "Repeated actor refresh accumulated demand")
	check(registry.TrySleepActor("npc") and cells.PinnedChunkCount == 0 and registry.IsDormant("npc"), "Ambient dormancy did not release scene pins")
	actor = registry.WakeActor("npc")
	check(actor != null and cells.PinnedChunkCount == 9, "Waking actor did not reacquire pins")
	registry.ChunkCellDataPath = NodePath("../Other")
	check(cells.PinnedChunkCount == 0 and other.PinnedChunkCount == 9, "Actor binding retained old-world pins")
	registry.ActorChunkRadius = 0
	grid.position = Vector2(400, 120)
	grid.Projection = 1
	actor.get_parent().global_position = grid.CellToWorld(Vector2i(-1, -33))
	actor.SynchronizePosition()
	check(other.PinnedChunkCount == 1 and other.IsChunkPinned(left), "Transformed isometric projection pinned the wrong chunk")
	host.remove_child(registry)
	check(other.PinnedChunkCount == 0, "Detached registry retained actors' pins")
	host.add_child(registry)
	check(other.IsChunkPinned(left), "Registry reattachment did not refresh live actors")
	host.remove_child(other)
	check(other.PinnedChunkCount == 0, "Detached cell service retained owner subscriptions")
	host.add_child(other)
	registry.RefreshChunkPins()
	check(other.IsChunkPinned(left), "Cell service reattachment fooled actor pin cache")
	other.name = "RenamedCells"
	actor.SynchronizePosition()
	check(other.PinnedChunkCount == 0, "Renamed cell service retained cached actor pins")
	other.name = "Other"
	actor.SynchronizePosition()
	check(other.IsChunkPinned(left), "Restored service name did not invalidate missing binding")
	grid.name = "RenamedGrid"
	actor.SynchronizePosition()
	check(other.PinnedChunkCount == 0, "Renamed grid retained cached actor pins")
	grid.name = "Grid"
	actor.SynchronizePosition()
	check(other.IsChunkPinned(left), "Restored grid name did not invalidate missing binding")
	host.remove_child(other)
	var replacement := make("grid/GridCellDataComponent", "Other", host, {})
	actor.SynchronizePosition()
	check(replacement.IsChunkPinned(left) and other.PinnedChunkCount == 0, "Same-path replacement did not refresh actor binding")
	replacement.free()
	actor.SynchronizePosition()
	host.add_child(other)
	actor.SynchronizePosition()
	check(other.IsChunkPinned(left), "Freed service left a stale cached binding")
	registry.RemoveActor("npc")
	check(other.PinnedChunkCount == 0, "Removed actor retained pins")
	host.free()
	await process_frame
	print("[terrain-chunk-pins] OK" if failures.is_empty() else "[terrain-chunk-pins] FAILED")
	quit(0 if failures.is_empty() else 1)
