extends SceneTree
const CELLS = preload("res://addons/beep_game_builder_cs/ecs/grid/GridCellDataComponent.cs")
const NAV = preload("res://addons/beep_game_builder_cs/ecs/grid/GridNavigationComponent.cs")

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var host := Node.new()
	root.add_child(host)
	var cells = CELLS.new()
	cells.name = "Cells"
	host.add_child(cells)
	var nav = NAV.new()
	nav.set("CellDataPath", NodePath("../Cells"))
	nav.set("BoundsSize", Vector2i(5, 3))
	host.add_child(nav)
	for y in range(3):
		for x in range(2, 5):
			cells.call("SetMetadata", Vector2i(x, y), "terrain_relief", 1)
	var low := Vector2i(1, 1)
	var high := Vector2i(2, 1)
	assert(nav.call("FindCellPath", Vector2i(0, 1), Vector2i(4, 1)).is_empty(), "Path crossed cliff without a ramp")
	assert(not nav.call("CanTraverse", low, high))
	cells.call("SetMetadata", low, "terrain_ramp_direction", Vector2i.RIGHT)
	assert(nav.call("CanTraverse", low, high) and nav.call("CanTraverse", high, low), "Ramp should work uphill and downhill")
	var path = nav.call("FindCellPath", Vector2i(0, 1), Vector2i(4, 1))
	assert(not path.is_empty() and low in path and high in path, "Path did not use ramp")
	for i in range(1, path.size()):
		assert(nav.call("CanTraverse", path[i - 1], path[i]), "Path contains illegal edge")
	cells.call("SetMetadata", low, "terrain_ramp_direction", Vector2i.UP)
	assert(not nav.call("CanTraverse", low, high), "Wrong-way ramp crossed cliff")
	cells.call("SetMetadata", low, "terrain_ramp_direction", Vector2i.RIGHT)
	cells.call("SetTerrainKind", high, "water")
	assert(not nav.call("CanTraverse", low, high), "Ramp bypassed blocked water")
	cells.call("SetTerrainKind", high, "grass")
	var snapshot = cells.call("GetCells")
	cells.call("ClearCells")
	cells.call("LoadCells", snapshot, true)
	assert(nav.call("CanTraverse", low, high), "Saved ramp did not restore")
	cells.call("SetMetadata", high, "terrain_relief", 2)
	assert(not nav.call("CanTraverse", low, high), "Ramp jumped two relief levels")
	nav.set("MaximumStepHeight", 2)
	assert(nav.call("CanTraverse", low, high), "Explicit step allowance was ignored")
	nav.set("MaximumStepHeight", 0)
	cells.call("ClearCells")
	cells.call("SetMetadata", Vector2i(1, 0), "terrain_relief", 1)
	nav.set("Diagonals", 1)
	assert(not nav.call("CanTraverse", Vector2i.ZERO, Vector2i.ONE), "Diagonal crossed a cliff corner")
	nav.set("RespectTerrainHeight", false)
	assert(nav.call("CanTraverse", Vector2i.ZERO, Vector2i.ONE), "Height-independent movement was not honored")
	host.free()
	print("[terrain-navigation-height] OK")
	quit()
