extends "res://tests/terrain_job_reservations_probe.gd"

func queue(host: Node, label: String, map: String) -> Node:
	var result: Node = load(BASE + "GridJobQueueComponent.cs").new()
	result.name = label
	result.ChunkCellDataPath = NodePath("../" + map)
	result.RequeueClaimedJobsOnLoad = false
	host.add_child(result)
	return result

func run() -> void:
	var host := Node.new()
	root.add_child(host)
	for label in ["Cells", "OtherCells"]:
		var cells: Node = load(BASE + "GridCellDataComponent.cs").new()
		cells.name = label
		host.add_child(cells)
	var a := queue(host, "A", "Cells")
	var b := queue(host, "B", "Cells")
	var isolated := queue(host, "Isolated", "OtherCells")
	var first: String = a.AddJob(Vector2i(4, 4), "build", 1.0, 0)
	var conflict: String = b.AddJob(Vector2i(4, 4), "inspect", 1.0, 100)
	var free: String = b.AddJob(Vector2i(5, 4), "build", 1.0, 0)
	check(a.ClaimJob(first, "worker"), "Initial claim failed")
	check(not b.CanClaimJob(conflict, "other") and not b.ClaimJob(conflict, "other"), "Queues shared a standing cell")
	check(not b.ClaimJob(free, "worker"), "Worker claimed jobs in two queues")
	check(b.ClaimNextJob("other", Vector2i.ZERO, []) == free, "Automatic claim did not skip foreign reservation")
	check(not a.TryReserveWorkCell(first, "worker", Vector2i(5, 4)), "Fallback overwrote another queue")
	check(a.GetReservedWorkCell(first) == Vector2i(4, 4), "Failed fallback lost old reservation")
	var separate: String = isolated.AddJob(Vector2i(4, 4), "build", 1.0, 0)
	check(isolated.ClaimJob(separate, "worker"), "Separate maps shared claims")
	check(a.TryReserveWorkCell(first, "worker", Vector2i(96, 96)), "Free fallback failed")
	check(b.ClaimJob(conflict, "third"), "Moving a reservation did not free the cell")
	a.ReleaseJob(first, "worker")
	check(a.ClaimJob(first, "worker") == false, "Released job stole a newly claimed original cell")
	b.ClearJobs()
	check(a.ClaimJob(first, "worker"), "Clear did not release shared reservations")
	# A saved conflicting claim cannot override an existing queue's live claim.
	b.LoadJobs([{"id": first, "cell": Vector2i(4, 4), "state": "Claimed", "claimed_by": "saved"}], true)
	check(b.ClaimedCount == 0 and b.QueuedCount == 1, "Restore overwrote another queue's claim")
	b.ClearJobs()
	check(not b.ClaimJob(first, "saved"), "Clear recreated a removed job")
	check(a.FindClaimedJobId("worker") == first, "Same job ID in another queue released the wrong claim")
	host.remove_child(a)
	var replacement: String = b.AddJob(Vector2i(4, 4), "build", 1.0, 0)
	check(b.ClaimJob(replacement, "worker"), "Detach leaked shared claims")
	host.add_child(a)
	check(a.ClaimedCount == 0, "Reattachment overwrote a claim acquired while detached")
	b.CompleteJob(replacement, "worker")
	check(a.ClaimJob(first, "worker"), "Completion did not release shared claims")
	# Rebinding releases only this queue's old-map reservations.
	a.ChunkCellDataPath = NodePath("../OtherCells")
	check(a.ClaimedCount == 0, "Rebinding accepted a conflicting worker on the new map")
	var rebound: String = b.AddJob(Vector2i(4, 4), "build", 1.0, 0)
	check(b.ClaimJob(rebound, "worker"), "Rebinding retained old-map reservation")
	a.ChunkCellDataPath = NodePath("../Missing")
	check(not a.ClaimJob(first, "nobody"), "Missing explicit map fell back to unscoped claims")
	a.ChunkCellDataPath = NodePath("../Cells")
	a.ClearJobs()
	b.ClearJobs()
	first = a.AddJob(Vector2i.ZERO, "build", 1.0, 0)
	conflict = b.AddJob(Vector2i.ZERO, "inspect", 1.0, 0)
	var raced := [true]
	var on_claim := func(_id, _worker): raced[0] = b.ClaimJob(conflict, "observer")
	a.JobClaimed.connect(on_claim)
	check(a.ClaimJob(first, "worker") and not raced[0], "Claim callback raced cross-queue reservation publication")
	a.JobClaimed.disconnect(on_claim)
	var on_release := func(_id, _worker): raced[0] = b.ClaimJob(conflict, "observer")
	a.JobReleased.connect(on_release)
	a.ReleaseJob(first, "worker")
	check(raced[0], "Release callback saw stale cross-queue reservation")
	a.JobReleased.disconnect(on_release)
	host.free()
	print("[cross-queue-reservations] OK" if failures.is_empty() else "[cross-queue-reservations] FAILED")
	quit(0 if failures.is_empty() else 1)
