extends SceneTree

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var host := Node2D.new()
	root.add_child(host)
	var cells: Node = load("res://addons/beep_game_builder_cs/ecs/grid/GridCellDataComponent.cs").new()
	cells.name = "Cells"
	host.add_child(cells)
	var generator: Node = load("res://addons/beep_game_builder_cs/ecs/terrain/TerrainGeneratorComponent.cs").new()
	generator.name = "Generator"
	generator.set("CellDataPath", NodePath("../Cells"))
	host.add_child(generator)
	var world: Node = load("res://addons/beep_game_builder_cs/ecs/terrain/TerrainWorldComponent.cs").new()
	world.set("BuildOnReady", false)
	world.set("ParticipatesInSave", false)
	world.set("GeneratorPath", NodePath("../Generator"))
	world.set("UseCustomBounds", true)
	world.set("CustomBounds", Vector2i(24, 36))
	world.set("UseCustomLandCoverage", true)
	world.set("LandCoverage", 0.7)
	world.set("UseCustomClimateSpan", true)
	world.set("ClimateLatitudeSpan", 0.0024)
	host.add_child(world)
	world.call("NewWorld")
	assert(world.get("BuiltSize") == Vector2i(24, 36))
	assert(cells.get("CellCount") == 864)
	assert(is_equal_approx(generator.get("LandmassScale"), 0.7))
	var diagnostics: Dictionary = world.call("Diagnostics")
	assert(absf(diagnostics["land_footprint_coverage"] - 0.7) < 0.08, "Land footprint must follow recipe")
	var saved: Dictionary = world.call("CaptureState")
	assert(saved["version"] == 5 and saved["use_custom_bounds"] and saved["start_area_radius"] == 0)
	assert(saved["start_distance_scaling"] == 0.0, "a world that scales nothing by distance saves zero")
	assert(generator.get("UseCustomClimateSpan") and generator.get("UseScaleRules"))
	assert(is_equal_approx(generator.get("ClimateLatitudeSpan"), 0.0024))
	cells.call("SetTerrainKind", Vector2i(2, 3), "probe_edit")
	world.set("CustomBounds", Vector2i(48, 48))
	world.set("LandCoverage", 0.3)
	world.set("ClimateLatitudeSpan", 0.8)
	world.call("RestoreState", saved)
	assert(is_equal_approx(generator.get("ClimateLatitudeSpan"), 0.0024), "Restore lost regional climate scale")
	assert(world.get("BuiltSize") == Vector2i(24, 36))
	assert(is_equal_approx(generator.get("LandmassScale"), 0.7))
	assert(cells.call("GetTerrainKind", Vector2i(2, 3)) == "probe_edit")
	world.set("LandCoverage", 0.98)
	world.call("NewWorld")
	assert(cells.call("GetTerrainKind", Vector2i(2, 3)) == "probe_edit", "Invalid coverage must not destroy live state")
	world.set("LandCoverage", 0.7)
	for invalid in [2.5, -0.5, NAN]:
		world.set("StartDistanceScaling", invalid)
		world.call("NewWorld")
		assert(cells.call("GetTerrainKind", Vector2i(2, 3)) == "probe_edit", "Invalid start-distance scaling %s must not destroy live state" % invalid)
	world.set("StartDistanceScaling", 0.0)
	world.set("CustomBounds", Vector2i(0, 36))
	world.call("NewWorld")
	assert(world.get("BuiltSize") == Vector2i(24, 36), "Invalid bounds must not replace last built size")
	world.set("UseCustomBounds", false)
	world.set("UseCustomLandCoverage", false)
	world.set("UseCustomClimateSpan", false)
	world.set("MapSize", 0)
	world.call("NewWorld")
	assert(world.get("BuiltSize") == Vector2i(32, 32))
	assert(cells.get("CellCount") == 1024)
	assert(not generator.get("UseCustomClimateSpan"), "Automatic climate must resume when override is disabled")
	assert(not is_equal_approx(generator.get("LandmassScale"), 0.7), "Preset must resume after override is disabled")
	host.free()
	print("[terrain-exact-recipe] OK")
	quit()
