extends SceneTree

const ECS := "res://addons/beep_game_builder_cs/ecs/"
var failures: Array[String] = []

func check(ok: bool, message: String) -> void:
	if not ok:
		failures.append(message)
		push_error(message)

func make(path: String, parent: Node, label: String, properties: Dictionary = {}) -> Node:
	var node: Node = load(ECS + path + ".cs").new()
	node.name = label
	for key in properties: node.set(key, properties[key])
	parent.add_child(node)
	return node

func settle(nav: Node, follower: Node) -> void:
	for i in 2000:
		nav.ProcessPathRequests()
		if not follower.IsPathPending: break
	check(not follower.IsPathPending, "Follower did not finish pending search")

func _initialize() -> void: run.call_deferred()

func run() -> void:
	var host := Node2D.new()
	root.add_child(host)
	current_scene = host
	var grid := make("grid/GridProjectionComponent", host, "Grid", {"DrawGrid": false, "TileSize": Vector2(32, 32)})
	var cells := make("grid/GridCellDataComponent", host, "Cells")
	var nav := make("grid/GridNavigationComponent", host, "Navigation", {"GridPath": grid.get_path(), "CellDataPath": cells.get_path(), "BoundsSize": Vector2i(64, 64), "PathExpansionsPerFrame": 16})
	var body := Node2D.new()
	host.add_child(body)
	body.global_position = grid.CellToWorld(Vector2i.ZERO)
	var follower := make("grid/GridPathFollowerComponent", body, "Follower", {"GridPath": grid.get_path(), "NavigationPath": nav.get_path(), "DriveCharacterBody": false, "Speed": 10000.0, "SetZIndexFromY": false})
	check(not follower.is_physics_processing(), "Idle follower still receives physics callbacks")
	var registry := make("actors/ActorRegistryComponent", host, "Registry")
	var actor := make("actors/ActorComponent", body, "Actor", {"ActorId": "worker", "RegistryPath": registry.get_path()})
	actor.set_physics_process(false)
	var events := []
	follower.MoveFailed.connect(func(_x, _y, reason): events.append(reason))
	check(follower.MoveToCell(Vector2i(60, 60)), "Request was not accepted")
	check(follower.is_physics_processing(), "Pending route did not enable physics callbacks")
	follower.AutoAdvancePath = false
	check(not follower.is_physics_processing(), "External-clock mode did not disable automatic movement")
	follower.AutoAdvancePath = true
	check(follower.is_physics_processing(), "Automatic movement did not resume pending route")
	check(follower.IsMoving and follower.IsPathPending and not follower.HasReachedDestination, "Pending request looked idle or arrived")
	check(follower.GetWorldPath().is_empty(), "Request searched synchronously")
	follower.MoveToCell(Vector2i(60, 60))
	check(nav.PendingPathRequestCount == 1, "Repeated target duplicated pending work")
	var before: Vector2 = body.global_position
	follower.AdvancePath(100.0)
	check(body.global_position == before, "Actor moved before search completion")
	follower.CancelMove()
	check(nav.PendingPathRequestCount == 0 and not follower.IsMoving, "Cancel retained search or motor ownership")
	check(not follower.is_physics_processing(), "Cancelled follower kept physics callbacks")
	follower.AutoAdvancePath = false
	follower.MoveToCell(Vector2i(60, 60))
	check(not follower.is_physics_processing(), "New order overrode external-clock mode")
	follower.AutoAdvancePath = true
	follower.MoveToCell(Vector2i(50, 50))
	check(nav.PendingPathRequestCount == 1, "Replacement retained old request")
	nav.ProcessPathRequests()
	cells.SetTerrainKind(Vector2i(10, 10), "deep_water")
	settle(nav, follower)
	check(follower.IsMoving and events.is_empty(), "Transient world edit did not retry pending search")
	for point in follower.GetWorldPath(): check(grid.WorldToCell(point) != Vector2i(10, 10), "Retried path crossed new water")
	follower.CancelMove()
	follower.MoveToCell(Vector2i(12, 12))
	var saved: Dictionary = JSON.parse_string(JSON.stringify(actor.CaptureActor()))
	follower.CancelMove()
	body.global_position = grid.CellToWorld(Vector2i(20, 20))
	actor.RestoreActor(saved)
	check(follower.IsMoving and follower.IsPathPending and nav.PendingPathRequestCount == 1, "Pending save did not restore a fresh request")
	settle(nav, follower)
	follower.AdvancePath(100.0)
	check(follower.HasReachedDestination and grid.WorldToCell(body.global_position) == Vector2i(12, 12), "Restored request missed destination")
	check(not follower.is_physics_processing(), "Arrived follower kept physics callbacks")
	follower.MoveToCell(Vector2i(63, 63))
	var container := Node2D.new()
	host.add_child(container)
	body.reparent(container)
	check(nav.PendingPathRequestCount == 1 and follower.IsPathPending, "Reparent lost or duplicated search")
	check(follower.is_physics_processing(), "Reparented pending route did not resume physics callbacks")
	settle(nav, follower)
	check(follower.IsMoving, "Reparented request did not install route")
	follower.CancelMove()
	follower.MoveToCell(Vector2i.ZERO)
	nav.ClearPathRequests()
	follower.AdvancePath(0.1)
	check(not follower.IsMoving and follower.LastMoveFailure == "navigation_request_lost", "Cleared service left follower pending forever")
	follower.MoveToCell(Vector2i.ZERO)
	follower.GridPath = NodePath("Missing")
	check(not follower.MoveToWorld(Vector2.ZERO) and nav.PendingPathRequestCount == 0, "Rejected world move retained old request")
	follower.GridPath = grid.get_path()
	body.global_position = grid.CellToWorld(Vector2i.ZERO)
	for y in 64: nav.SetBlocked(Vector2i(32, y), true)
	var jobs := make("grid/GridJobQueueComponent", host, "Jobs", {"RemoveCompletedJobs": false})
	var worker := make("grid/GridWorkerComponent", body, "Worker", {"GridPath": grid.get_path(), "JobQueuePath": jobs.get_path(), "PathFollowerPath": follower.get_path(), "AutoClaimJobs": false})
	worker.set_process(false)
	var job: String = jobs.AddJob(Vector2i(2, 0), "prepare", 1.0, 0)
	jobs.SetJobApproachCell(job, Vector2i(50, 50))
	check(worker.AssignJob(job), "Worker did not accept scheduled approach")
	var worker_save: Dictionary = JSON.parse_string(JSON.stringify(actor.CaptureActor()))
	worker.CancelCurrentJob("save_test")
	actor.RestoreActor(worker_save)
	check(worker.CurrentJobId == job and follower.IsPathPending, "Pending worker save lost claim or path request")
	worker.Tick(0.1)
	check(not worker.IsWorking, "Pending approach started remote work")
	settle(nav, follower)
	worker.Tick(0.1)
	check(follower.IsPathPending and follower.DestinationCell == Vector2i(2, 0), "Failed approach did not schedule job-cell fallback")
	settle(nav, follower)
	follower.AdvancePath(100.0)
	worker.Tick(0.1)
	check(worker.IsWorking and follower.HasReachedDestination, "Fallback did not start work after actual arrival")
	worker.CancelCurrentJob("test")
	var depot: Node = load("res://tests/actor_test_depot.gd").new()
	depot.name = "Depot"
	host.add_child(depot)
	var hauler := make("grid/GridHaulerComponent", body, "Hauler", {"PathFollowerPath": follower.get_path(), "DepotStoragePath": depot.get_path(), "DepotCell": Vector2i(3, 0), "RegisterOnReady": false})
	hauler.set_process(false)
	check(hauler.RequestHaul(Vector2i(4, 0), "wood", 3) and follower.IsPathPending, "Hauler did not queue pickup path")
	var haul_save: Dictionary = JSON.parse_string(JSON.stringify(actor.CaptureActor()))
	hauler.CancelHaul("save_test")
	actor.RestoreActor(haul_save)
	check(follower.IsPathPending and hauler.Stored("wood") == 3, "Pending haul save lost cargo or path")
	settle(nav, follower)
	follower.AdvancePath(100.0)
	hauler.AdvanceWork(1.0)
	check(follower.IsPathPending and depot.Stored("wood") == 0, "Hauler delivered before reaching depot")
	settle(nav, follower)
	follower.AdvancePath(100.0)
	hauler.AdvanceWork(1.0)
	check(hauler.Stored("wood") == 0 and depot.Stored("wood") == 3, "Pending haul restore lost or duplicated delivery")
	follower.MoveToCell(Vector2i(20, 20))
	body.free()
	check(nav.PendingPathRequestCount == 0, "Freed actor retained queued work")
	host.free()
	var smoke: Node = load("res://tests/GridPlacementSmoke.cs").new()
	root.add_child(smoke)
	check(smoke.RunFollowerChecks(), "Existing follower fixtures failed: " + str(smoke.Failure))
	smoke.free()
	print("[terrain-follower-requests] OK" if failures.is_empty() else "[terrain-follower-requests] FAILED")
	quit(0 if failures.is_empty() else 1)
