extends SceneTree

const GRID := "res://addons/beep_game_builder_cs/ecs/grid/"
var failures: Array[String] = []
func check(ok: bool, message: String) -> void:
	if not ok:
		failures.append(message)
		push_error(message)
func _initialize() -> void: run.call_deferred()
func run() -> void:
	var host := Node.new()
	root.add_child(host)
	var cells: Node = load(GRID + "GridCellDataComponent.cs").new()
	cells.name = "Cells"
	host.add_child(cells)
	var archive: Node = load(GRID + "GridCellArchiveComponent.cs").new()
	archive.CellDataPath = NodePath("../Cells")
	archive.ArchiveDirectory = "user://tests/chunk_eviction_%s_%s" % [OS.get_process_id(), Time.get_ticks_usec()]
	host.add_child(archive)
	var at := Vector2i(-1, -1)
	var chunk := Vector2i(-1, -1)
	cells.SetTerrainKind(at, "forest")
	cells.SetTerrainKind(Vector2i.ZERO, "desert")
	check(not archive.EvictSavedChunk(chunk) and cells.CellCount == 2, "Unsaved cells were evicted")
	check(archive.SaveChunk(chunk), "Initial save failed")
	cells.SetMetadata(at, "count", 7)
	check(not archive.EvictSavedChunk(chunk), "Newer edits were discarded")
	check(archive.SaveChunk(chunk), "Resave failed")
	cells.SetChunkPins(host, [chunk])
	check(not archive.EvictSavedChunk(chunk) and cells.CellCount == 2, "Pinned chunk evicted")
	cells.ReleaseChunkPins(host)
	var path: String = archive.GetChunkPath(chunk)
	var saved := FileAccess.get_file_as_bytes(path)
	DirAccess.remove_absolute(path)
	check(not archive.EvictSavedChunk(chunk) and cells.CellCount == 2, "Missing archive discarded live data")
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string("corrupted")
	file.close()
	check(not archive.EvictSavedChunk(chunk) and cells.CellCount == 2, "Changed archive discarded live data")
	file = FileAccess.open(path, FileAccess.WRITE)
	file.store_buffer(saved)
	file.close()
	var revision: int = cells.GetChunkRevision(chunk)
	check(archive.EvictSavedChunk(chunk), "Saved idle chunk could not be evicted")
	check(cells.CellCount == 1 and cells.StoredChunkCount == 1 and cells.EvictedChunkCount == 1, "Eviction did not release physical records")
	check(not cells.SetChunkAvailable(chunk, true) and not cells.IsChunkAvailable(chunk), "Readiness exposed missing archived records")
	check(cells.GetChunkRevision(chunk) == revision, "Eviction altered content version")
	var smoke: Node = load("res://tests/CoreGameplaySmoke.cs").new()
	host.add_child(smoke)
	check(smoke.CheckEvictedWrites(cells), smoke.Failure)
	check(archive.LoadChunk(chunk) and cells.GetTerrainKind(at) == "forest" and cells.GetMetadata(at, "count") == 7, "Archived chunk failed exact reload")
	check(cells.IsChunkAvailable(chunk) and cells.EvictedChunkCount == 0, "Reload did not restore residency")
	cells.Till(at)
	cells.PlantCrop(at, "wheat", 3, -1)
	check(archive.SaveChunk(chunk) and not archive.EvictSavedChunk(chunk), "Crop simulation was evicted")
	cells.AdvanceDay(1)
	check(cells.GetCropAgeDays(at) == 1, "Resident crop stopped simulating")
	cells.RemoveCrop(at, false)
	cells.Water(at)
	check(archive.SaveChunk(chunk) and not archive.EvictSavedChunk(chunk), "Water expiration state was evicted")
	cells.AdvanceDay(1)
	check(archive.SaveChunk(chunk) and archive.EvictSavedChunk(chunk), "Idle field remained unevictable")
	var id: int = archive.RequestLoadChunk(chunk)
	check(not archive.EvictSavedChunk(Vector2i.ZERO) and archive.LastError == "archive_busy", "Eviction overlapped archive I/O")
	var deadline := Time.get_ticks_msec() + 10000
	while archive.IsBusy and Time.get_ticks_msec() < deadline: await process_frame
	check(id > 0 and not archive.IsBusy and cells.IsChunkAvailable(chunk), "Asynchronous reload failed")
	check(archive.SaveChunk(chunk) and archive.EvictSavedChunk(chunk), "Second eviction failed")
	cells.ClearCells()
	check(cells.EvictedChunkCount == 0 and cells.SetChunkAvailable(chunk, true), "Whole-world clear retained eviction markers")
	cells.SetTerrainKind(at, "forest")
	check(archive.SaveChunk(chunk) and archive.EvictSavedChunk(chunk), "Generation replacement fixture failed")
	var generator: Node = load("res://addons/beep_game_builder_cs/ecs/terrain/TerrainGeneratorComponent.cs").new()
	generator.CellDataPath = NodePath("../Cells")
	generator.BoundsSize = Vector2i(4, 4)
	generator.DefaultTerrainKind = "mud"
	host.add_child(generator)
	check(generator.GenerateTerrain() == 16 and cells.EvictedChunkCount == 0 and cells.DefaultTerrainKind == "mud", "New generation could not replace archived world/default terrain")
	var world: Dictionary = cells.CaptureChunkState()
	check(archive.SaveChunk(chunk) and archive.EvictSavedChunk(chunk) and cells.IsChunkEvicted(chunk), "Empty default chunk could not detach")
	cells.RestoreChunkState(world)
	check(cells.EvictedChunkCount == 0 and cells.CellCount == 16, "Full restore did not clear empty-chunk eviction")
	DirAccess.remove_absolute(path)
	DirAccess.remove_absolute(ProjectSettings.globalize_path(archive.ArchiveDirectory))
	host.free()
	print("[terrain-chunk-eviction] OK" if failures.is_empty() else "[terrain-chunk-eviction] FAILED")
	quit(0 if failures.is_empty() else 1)
