extends SceneTree

# Regression tests for the workflow review findings.
const CLOCK = preload("res://addons/beep_game_builder_cs/ecs/time/GameClock.cs")
const WORK_CLOCK = preload("res://addons/beep_game_builder_cs/ecs/grid/GridWorkClockComponent.cs")
const JOBS = preload("res://addons/beep_game_builder_cs/ecs/grid/GridJobQueueComponent.cs")
const WALLET = preload("res://addons/beep_game_builder_cs/ecs/grid/GridResourceWalletComponent.cs")
const PRODUCTION = preload("res://addons/beep_game_builder_cs/ecs/grid/GridProductionComponent.cs")
const CATALOG = preload("res://addons/beep_game_builder_cs/ecs/grid/GridBuildCatalogComponent.cs")
const SITES = preload("res://addons/beep_game_builder_cs/ecs/grid/GridBuildSiteComponent.cs")
const STORAGE = preload("res://addons/beep_game_builder_cs/ecs/grid/GridStorageComponent.cs")
const GRID = preload("res://addons/beep_game_builder_cs/ecs/grid/GridProjectionComponent.cs")
const NAV = preload("res://addons/beep_game_builder_cs/ecs/grid/GridNavigationComponent.cs")
const FOLLOWER = preload("res://addons/beep_game_builder_cs/ecs/grid/GridPathFollowerComponent.cs")
const WORKER = preload("res://addons/beep_game_builder_cs/ecs/grid/GridWorkerComponent.cs")
var failures: Array[String] = []
var site_events := 0

func _initialize() -> void:
	call_deferred("run")

func check(ok: bool, message: String) -> void:
	if not ok:
		failures.append(message)
		print("[workflow-review] FAIL: " + message)

func run() -> void:
	var world := Node.new()
	root.add_child(world)
	var clock = CLOCK.new()
	clock.call("Configure", 0, 10.0)
	world.add_child(clock)
	clock.set_process(false)
	var work = WORK_CLOCK.new()
	work.name = "WorkClock"
	world.add_child(work)
	clock.call("Configure", 0, 100.0)
	clock.call("Advance", 100.0)
	check(is_equal_approx(float(work.get("ElapsedTurns")), 1.0), "W01: day-length reconfigure produced %s work turns, expected 1" % work.get("ElapsedTurns"))
	var jobs = JOBS.new()
	jobs.name = "Jobs"
	world.add_child(jobs)
	var id = jobs.call("AddJob", Vector2i.ZERO, "build", 10.0, 0)
	jobs.call("ReportProgress", id, 3.0)
	var saved = jobs.call("GetJobs")
	jobs.call("LoadJobs", saved, true)
	check(is_equal_approx(float(jobs.call("GetJobProgress01", id)), 0.7), "W02: job save/load discarded 70 percent progress")
	var grid = GRID.new()
	grid.name = "Grid"
	world.add_child(grid)
	var nav = NAV.new()
	nav.name = "Nav"
	nav.set("GridPath", NodePath("../Grid"))
	world.add_child(nav)
	var unit := Node2D.new()
	var follower = FOLLOWER.new()
	follower.name = "Follower"
	follower.set("GridPath", NodePath("../../Grid"))
	follower.set("NavigationPath", NodePath("../../Nav"))
	follower.set("SetZIndexFromY", false)
	unit.add_child(follower)
	var worker = WORKER.new()
	worker.set("GridPath", NodePath("../../Grid"))
	worker.set("JobQueuePath", NodePath("../../Jobs"))
	worker.set("PathFollowerPath", NodePath("../Follower"))
	worker.set("WorkClockPath", NodePath("../../WorkClock"))
	worker.set("WorkerId", "resume_worker")
	unit.add_child(worker)
	world.add_child(unit)
	unit.global_position = grid.call("CellToWorld", Vector2i.ZERO)
	check(worker.call("AssignJob", id), "Worker could not reclaim restored job")
	nav.ProcessPathRequests()
	follower.call("AdvancePath", 0.01)
	worker.call("Tick", 0.01)
	check(is_equal_approx(float(worker.get("WorkRemainingTurns")), 3.0), "Worker restarted total work instead of remaining work")
	worker.set("IsActive", false)
	work.call("AdvanceTurns", 1.0)
	check(is_equal_approx(float(worker.get("WorkRemainingTurns")), 3.0), "Inactive worker advanced from clock signal")
	unit.free()
	check(int(jobs.call("GetJobState", id)) == 0, "Removed worker left job claimed")
	jobs.call("ClearJobs")
	var wallet = WALLET.new()
	wallet.name = "Wallet"
	world.add_child(wallet)
	var production = PRODUCTION.new()
	production.set("ResourceWalletPath", NodePath("../Wallet"))
	production.set("WorkClockPath", NodePath("../WorkClock"))
	production.set("ConsumeInputsOnStart", false)
	production.set("Loop", false)
	production.set("Recipes", [{"recipe_id":"planks", "duration_turns":1.0, "inputs":[{"resource_id":"wood", "amount":5}], "outputs":[{"resource_id":"plank", "amount":1}]}])
	world.add_child(production)
	production.call("StartProduction", "planks")
	production.call("AdvanceWork", 1.0)
	check(int(wallet.call("GetAmount", "plank")) == 0, "W03: deferred-input recipe created output with zero inputs")
	wallet.call("SetAmount", "wood", 5)
	production.call("AdvanceWork", 1.0)
	check(int(wallet.call("GetAmount", "wood")) == 0 and int(wallet.call("GetAmount", "plank")) == 1, "Deferred recipe did not debit once when inputs arrived")
	check(not production.call("CompleteProduction"), "Idle production completed twice")
	wallet.call("SetAmount", "wood", 10)
	production.set("ConsumeInputsOnStart", true)
	production.call("StartProduction", "planks")
	var cycle = production.call("CaptureState")
	production.set("ConsumeInputsOnStart", false)
	production.call("RestoreState", cycle)
	production.call("CancelProduction", true)
	production.call("CancelProduction", true)
	check(int(wallet.call("GetAmount", "wood")) == 10, "Restored paid cycle refund was lost or duplicated")
	production.set("ConsumeInputsOnStart", false)
	production.call("StartProduction", "planks")
	cycle = production.call("CaptureState")
	production.call("RestoreState", cycle)
	var reenter = func(_id, _amount):
		check(not production.call("CompleteProduction"), "Production completed reentrantly during resource notification")
	wallet.connect("ResourceChanged", reenter)
	production.call("AdvanceWork", 1.0)
	wallet.disconnect("ResourceChanged", reenter)
	check(int(wallet.call("GetAmount", "wood")) == 5 and int(wallet.call("GetAmount", "plank")) == 2, "Restored deferred cycle produced or charged twice")
	wallet.call("SetAmount", "wood", 10)
	var duplicate_costs = [{"resource_id":"wood", "amount":6}, {"resource_id":"WOOD", "amount":6}]
	check(not wallet.call("Spend", duplicate_costs) and int(wallet.call("GetAmount", "wood")) == 10, "Wallet accepted unaffordable duplicate cost entries")
	wallet.call("SetAmount", "stone", 4)
	var observe_debit = func(resource_id, _amount):
		if resource_id == "wood":
			check(int(wallet.call("GetAmount", "stone")) == 0, "Wallet signaled before committing all debits")
	wallet.connect("ResourceChanged", observe_debit)
	wallet.call("Spend", [{"resource_id":"wood", "amount":5}, {"resource_id":"stone", "amount":4}])
	wallet.disconnect("ResourceChanged", observe_debit)
	var catalog = CATALOG.new()
	catalog.name = "Catalog"
	catalog.set("Builds", [{"build_id":"depot", "build_turns":3, "required_materials":[{"resource_id":"wood", "amount":5}]}])
	world.add_child(catalog)
	var sites = SITES.new()
	sites.set("BuildCatalogPath", NodePath("../Catalog"))
	sites.set("JobQueuePath", NodePath("../Jobs"))
	world.add_child(sites)
	sites.connect("BuildSiteCreated", func(_build, _job, _placed, _x, _y): site_events += 1)
	var placed := Node2D.new()
	var storage = STORAGE.new()
	placed.add_child(storage)
	world.add_child(placed)
	storage.call("Load", "wood", 15)
	check(sites.call("RegisterPlacedBuild", "depot", placed, Vector2i.ZERO), "Fixture could not register build site")
	check(int(storage.call("Stored", "wood")) == 10 and site_events == 1, "W04: one site consumed %s wood and emitted %s creation events; expected 5 and 1" % [15 - int(storage.call("Stored", "wood")), site_events])
	check(not sites.call("RegisterPlacedBuild", "depot", placed, Vector2i.ZERO), "Registered the same construction twice")
	check(not storage.call("TryConsume", duplicate_costs) and int(storage.call("Stored", "wood")) == 10, "Storage consumed partial duplicate requirements")
	storage.call("Load", "stone", 4)
	check(storage.call("TryConsume", [{"resource_id":"wood", "amount":5}, {"resource_id":"stone", "amount":4}]), "Atomic multi-material consumption failed")
	check(int(storage.call("Stored", "wood")) == 5 and int(storage.call("Stored", "stone")) == 0, "Multi-material consumption left wrong balances")
	world.free()
	print("[workflow-review] OK" if failures.is_empty() else "[workflow-review] %s open regression(s)" % failures.size())
	quit(0 if failures.is_empty() else 1)
