using Godot;
using System;

public static class BeepProjectileGenerator
{
    public static string CreateProjectileMath(bool overwrite = false)
    {
        var path = "res://scripts/projectiles/projectile_math.gd";
        var code = @"## ProjectileMath - generated by Beep Game Builder (C#)
class_name ProjectileMath
extends RefCounted

static func sample_arc_points(start: Vector2, end: Vector2, height: float, steps: int = 16) -> PackedVector2Array:
	var points := PackedVector2Array()
	for i in range(steps):
		var t := float(i) / float(max(steps - 1, 1))
		var p := start.lerp(end, t); p.y -= sin(t * PI) * height
		points.append(p)
	return points

static func calculate_launch_velocity(start: Vector2, end: Vector2, gravity: float, time: float) -> Vector2:
	return Vector2((end.x - start.x) / time, (end.y - start.y - 0.5 * gravity * time * time) / time)

static func predict_position(start: Vector2, velocity: Vector2, gravity: float, time: float) -> Vector2:
	return start + velocity * time + Vector2(0, 0.5 * gravity * time * time)

static func find_time_to_target(start: Vector2, end: Vector2, speed: float) -> float:
	return start.distance_to(end) / max(speed, 0.01)

static func clamp_arc_height(height: float, min_h: float = 0.0, max_h: float = 500.0) -> float:
	return clamp(height, min_h, max_h)

static func draw_debug_arc(line: Line2D, points: PackedVector2Array) -> void:
	if not line: return; line.points = points
";
        BeepFileUtils.SafeWriteText(path, code, overwrite); return path;
    }

    public static string CreateProjectile2D(bool overwrite = false)
    {
        var path = "res://scripts/projectiles/projectile_2d.gd";
        var code = @"## Projectile2D - generated by Beep Game Builder (C#)
class_name Projectile2D
extends Area2D

@export var speed: float = 400.0
@export var gravity: float = 0.0
@export var max_lifetime: float = 5.0
@export var damage: float = 10.0

var velocity: Vector2 = Vector2.ZERO
var _life_timer: float = 0.0

signal hit(target: Node2D, position: Vector2)
signal expired

func launch(direction: Vector2, initial_speed: float = -1.0) -> void:
	var spd := speed if initial_speed < 0 else initial_speed
	velocity = direction.normalized() * spd
	body_entered.connect(_on_body_hit); area_entered.connect(_on_area_hit)

func _physics_process(delta: float) -> void:
	velocity.y += gravity * delta; global_position += velocity * delta
	_life_timer += delta
	if _life_timer >= max_lifetime: expired.emit(); queue_free()

func _on_body_hit(body: Node2D) -> void: hit.emit(body, global_position); queue_free()
func _on_area_hit(area: Area2D) -> void: hit.emit(area, global_position); queue_free()
";
        BeepFileUtils.SafeWriteText(path, code, overwrite); return path;
    }

    public static string CreateBasicProjectileScene(bool overwrite = false)
    {
        var path = "res://scenes/projectiles/basic_projectile.tscn";
        if (!overwrite && BeepFileUtils.FileExists(path)) { BeepFileUtils.Log($"Skipped: {path}"); return path; }
        var proj = new Area2D { Name = "BasicProjectile" };
        var col = new CollisionShape2D { Shape = new RectangleShape2D { Size = new Vector2(12, 4) } };
        proj.AddChild(col); col.Owner = proj;
        var packed = new PackedScene(); packed.Pack(proj); ResourceSaver.Save(packed, path);
        BeepFileUtils.Log($"Created: {path}"); return path;
    }

    public static string CreateArcProjectileScene(bool overwrite = false)
    {
        var path = "res://scenes/projectiles/arc_projectile.tscn";
        if (!overwrite && BeepFileUtils.FileExists(path)) { BeepFileUtils.Log($"Skipped: {path}"); return path; }
        var proj = new Area2D { Name = "ArcProjectile" };
        var col = new CollisionShape2D { Shape = new CircleShape2D { Radius = 6 } };
        proj.AddChild(col); col.Owner = proj;
        var packed = new PackedScene(); packed.Pack(proj); ResourceSaver.Save(packed, path);
        BeepFileUtils.Log($"Created: {path}"); return path;
    }

    public static string CreateProjectileById(string pid, bool overwrite = false)
    {
        var data = BeepFileUtils.LoadJson("res://addons/beep_game_builder_cs/catalogs/projectile_presets.json");
        if (!data.TryGetValue("presets", out var pv) || pv.VariantType != Variant.Type.Array) return "";
        foreach (var p in pv.AsGodotArray())
        {
            var d = p.AsGodotDictionary();
            if ((string)d["id"] == pid)
            {
                var fn = (string)d["helper_function"];
                var path = $"res://scripts/projectiles/{fn}.gd";
                var code = $"# {(string)d["display_name"]}\nclass_name {char.ToUpper(fn[0]) + fn[1..]}\nextends RefCounted\n\n{(string)d["code"]}";
                BeepFileUtils.SafeWriteText(path, code, overwrite); return path;
            }
        }
        BeepFileUtils.LogError($"Projectile preset not found: {pid}"); return "";
    }
}
